# Generated by Django 4.2.7 on 2023-12-02 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Marka')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('weight', models.FloatField(verbose_name='Ağırlık')),
                ('category', models.CharField(max_length=255, verbose_name='Kategori')),
                ('payload_capacity', models.FloatField(verbose_name='Yük Taşıma Kapasitesi')),
                ('range', models.FloatField(verbose_name='Uçuş Menzili')),
                ('max_speed', models.FloatField(verbose_name='Maksimum Hız')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Başlangıç Tarihi ve Saati')),
                ('end_datetime', models.DateTimeField(verbose_name='Bitiş Tarihi ve Saati')),
                ('iha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.iha', verbose_name='Kiralanan İHA')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kiralayan Üye')),
            ],
        ),
    ]
